### ISSUE TITLE
Current version throws errors when listing pages with waiting strings and edit a string

### ISSUE THREAD

**Issue by psmits1567** [vlad-timotei/wpgp-tools#72]
Fetching lines from consistency table delivers an error
caught TypeError: Cannot read properties of null (reading 'classList')
    at wpgpt-consistency.js:347:24
    at NodeList.forEach (<anonymous>)
    at wpgpt-consistency.js:342:25
    at Array.forEach (<anonymous>)
    at MutationObserver.<anonymous> (wpgpt-consistency.js:341:14)
(

**Comment by vlad-timotei** [comment]
Thanks, this will be fixed in [this release](https://github.com/vlad-timotei/wpgp-tools/tree/2.1.2) and it was fixed in t[his commit](https://github.com/vlad-timotei/wpgp-tools/commit/1c67dbeee37fb9084f7393bcb7e7324f0170e576).
